# Project
version=5.3.0
group=com.hrznstudio.emojiful

# Common
minecraft_version=26.1.2
common_runs_enabled=false
common_client_run_name=Common Client
common_server_run_name=Common Server

# NeoForge
neo_version=26.1.2.76
moddev_version=2.0.141

# Fabric
fabric_version=0.151.0+26.1.2
fabric_loader_version=0.19.3
fabric_loom_version=1.16-SNAPSHOT
midnightlib_version=1.9.3+26.1-fabric


# Mod options
mod_name=emojiful
mod_author=HorizonStudio
mod_id=emojiful
build_file_name=Emojiful

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.configuration-cache=false
