name: Publish action

on:
  create:
    tag:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "25"
          cache: gradle
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: Publish Minecraft Mods Fabric
        uses: Kir-Antipov/mc-publish@v3.3.1
        with:
          curseforge-id: 284324
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          modrinth-id: 72GXx2MO
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: |
            Fabric/build/libs/!(*-@(javadoc|sources)).jar
            Fabric/build/libs/*-@(javadoc|sources).jar
          version-type: beta
          environment: client | server
          loaders: |
            fabric
          game-versions: |
            26.1.2
          java: 25
          name: ""
          changelog: "https://github.com/InnovativeOnlineIndustries/Emojiful/commits/26.1.2"
      - name: Publish Minecraft Mods NeoForge
        uses: Kir-Antipov/mc-publish@v3.3.1
        with:
          curseforge-id: 284324
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          modrinth-id: 72GXx2MO
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: |
            NeoForge/build/libs/!(*-@(javadoc|sources)).jar
            NeoForge/build/libs/*-@(javadoc|sources).jar
          version-type: beta
          environment: client | server
          loaders: neoforge
          game-versions: |
            26.1.2
          java: 25
          name: ""
          changelog: "https://github.com/InnovativeOnlineIndustries/Emojiful/commits/26.1.2"
